### ISSUE TITLE
Lesson titles

### ISSUE THREAD

**Issue by oharac** [nceas-learning-hub/coreRlessons#2]
Currently, it looks like in the `session_XX.qmd` file, the YAML header includes a title for the lesson, e.g., `session_01.qmd` for the recent coreR looks like:
```
---
title: "Course Introduction"
title-block-banner: true
format:
  html:
    code-overflow: wrap
---

{{< include /sections/reproducibility-intro.qmd >}}
```
But, that title is nowhere to be found in `reproducibility-intro.qmd` so it looks like it has to be manually written for each `session_XX.qmd` document.  To automate this, I think there are a few options, not sure exactly which will work best:

* Option 1, if this works, would be cleanest: in the included qmd (here, `reproducibility-intro.qmd`), include a YAML header with title (and perhaps other metadata including author, date).  Drop the `title:` from the `session_01.qmd` and it should use the title from the included file instead.
* Option 2, if that doesn't work, include the metadata in a YAML header in the included qmd, but something that Quarto won't recognize, e.g., `lesson_title: blah blah blah` - we can grab that text automatically, populate the title field in `session_XX.qmd`, and Quarto will ignore the field in the included qmd.
* Option 3, include the title (and perhaps other metadata) in the included Quarto document, but in some other format that doesn't render, e.g., HTML comment `<!-- title: blah blah blah -->`.

In any case, this would require updating most or all of the lesson qmds to explicitly include a title (and perhaps other metadata) - which I think is a good thing!

**Comment by oharac** [comment]
For the sample lessons, I simply added a YAML header (or modified if there already was one) to include a `title: XXX` field.  When rendering the book, that title shows up in the nav bar and the top of the lesson.  A nice clean solution!

I removed the title from the `session_XX.qmd` templates, since it is redundant.

**Comment by camilavargasp** [comment]
I successfully created a mock book! 
However, some of the titles are not working when I render the book using `quarto preview`
Issues I'm seeing:
- TOC has `session_xx.html` name (see image below)
- Lesson 1 the header says: format: HTML and then below on text is says: title: “Reproducibility: a Lego Activity”
- Lesson 2 the title on the header banner looks good but the Learning Objective header is missing
- Lesson 3 has the learning Objective header , but the title on the banner says: title: Git and GitHub
- Lesson 4 the title on the header banner is not right (says: wrap: sentence). Actual title appears below as normal text (title: Tidy Data editor: markdown:)
- Lesson 5, same than lesson 3
- Lesson 6 title reads: title: Creating R Packages
- Lesson 7 titles reads: bibliography: book.bib. Actual title shows up on text (title: “Practice Session: Joins”)
- Lesson 8 same than lesson 2, plus some images are missing.

**Example pic**
<img width="1377" alt="image" src="https://github.com/user-attachments/assets/f6c25094-d319-4530-8044-65ae701fb3b3">

**Comment by oharac** [comment]
Hmm, it didn't show up like that on mine... let me see if I can replicate here, otherwise we can take a look at yours on Monday?

**Comment by camilavargasp** [comment]
You can try cloning the repo I created and then run `quarto preview` on the terminal and see what happens.

**Comment by oharac** [comment]
I cloned your repo and get those same issues... It seems to be related to the YAML header if it has more than one line in it.  Weird that it is inconsistent from one platform to another!  I should try it on my Macbook instead of Windows to see if it's specific to Mac

**Comment by oharac** [comment]
Try updating your packages - `devtools::install_github('nceas-learning-hub/coreR')` and `devtools::install_github('nceas-learning-hub/coreRlessons')` - I can't get the problem to replicate when running my own repo, so maybe there's something hiding in one of the older .yml files or whatnot.

Once you've updated packages, you can delete the lessons, images, data folders, and then run `coreR::setup_lessons(lessons = ..., overwrite = TRUE)` - see if it still happens for you!

**Comment by oharac** [comment]
Closing this for now - but will open a separate issue for important formatting things
